<a href="https://colab.research.google.com/github/bezerraluis/Luis_Paulo_Portf-lio/blob/master/Projeto_A%C3%A7%C3%A3o_humana_em_Fraude_de_cart%C3%A3o_de_cr%C3%A9dito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ação humana em fraudes de cartão de crédito

Criar um algoritmo que faça uma predição probabilistica com os dados de fraude de cartão de crédito e retorne os dados que possuem uma chance de 50% à 70% de ser fraude.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df_credit_card = pd.read_csv('creditcard.csv')
df_credit_card.head()

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [ ]:
x,y = df_credit_card.drop(['Class'],axis= 'columns'),df_credit_card.iloc[: ,[30]]

In [ ]:

df1 = df_credit_card[['Class','V1','V2','V3','V4','V5']]
df1

        Class         V1         V2        V3        V4        V5
0           0  -1.359807  -0.072781  2.536347  1.378155 -0.338321
1           0   1.191857   0.266151  0.166480  0.448154  0.060018
2           0  -1.358354  -1.340163  1.773209  0.379780 -0.503198
3           0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309
4           0  -1.158233   0.877737  1.548718  0.403034 -0.407193
...       ...        ...        ...       ...       ...       ...
284802      0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473
284803      0  -0.732789  -0.055080  2.035030 -0.738589  0.868229
284804      0   1.919565  -0.301254 -3.249640 -0.557828  2.630515
284805      0  -0.240440   0.530483  0.702510  0.689799 -0.377961
284806      0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546

[284807 rows x 6 columns]

In [ ]:
df_credit_card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [ ]:
df_credit_card.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression

In [ ]:
X_treino, X_teste, Y_treino, Y_teste = train_test_split(x, y.values, test_size=0.3, random_state=12)

In [ ]:
lr = LogisticRegression(solver='liblinear',random_state=42)

In [ ]:
lr.fit(X_treino ,Y_treino)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
predicoes = lr.predict_proba(X_teste)

In [ ]:
predicoes[: ,1]

array([3.27854740e-06, 1.00000000e+00, 9.25749529e-08, ...,
       1.80467079e-06, 4.75029956e-07, 6.91285605e-03])

In [ ]:
valores =[]

for pre in predicoes[: ,1]:
  if pre >= 0.5 and pre <= 0.7 :
      valores.append(pre)

In [ ]:
final =pd.DataFrame(valores)

In [ ]:
df_credit_card['Previsoes entre 50 e 70 %'] = final
df_credit_card.head(20)

    Time        V1        V2  ...  Amount  Class  Previsoes entre 50 e 70 %
0    0.0 -1.359807 -0.072781  ...  149.62      0                   0.581622
1    0.0  1.191857  0.266151  ...    2.69      0                   0.635597
2    1.0 -1.358354 -1.340163  ...  378.66      0                   0.594973
3    1.0 -0.966272 -0.185226  ...  123.50      0                   0.648762
4    2.0 -1.158233  0.877737  ...   69.99      0                   0.503887
5    2.0 -0.425966  0.960523  ...    3.67      0                   0.542824
6    4.0  1.229658  0.141004  ...    4.99      0                   0.593189
7    7.0 -0.644269  1.417964  ...   40.80      0                   0.534174
8    7.0 -0.894286  0.286157  ...   93.20      0                   0.659950
9    9.0 -0.338262  1.119593  ...    3.68      0                   0.665941
10  10.0  1.449044 -1.176339  ...    7.80      0                   0.648482
11  10.0  0.384978  0.616109  ...    9.99      0                   0.524053
12  10.0  1.249999 -1.221637  ...  121.50      0                   0.646957
13  11.0  1.069374  0.287722  ...   27.50      0                   0.691298
14  12.0 -2.791855 -0.327771  ...   58.80      0                   0.622415
15  12.0 -0.752417  0.345485  ...   15.99      0                   0.565422
16  12.0  1.103215 -0.040296  ...   12.99      0                        NaN
17  13.0 -0.436905  0.918966  ...    0.89      0                        NaN
18  14.0 -5.401258 -5.450148  ...   46.80      0                        NaN
19  15.0  1.492936 -1.029346  ...    5.00      0                        NaN

[20 rows x 32 columns]